name: Maven Package

on:
  push:
    tags: [ '*.*.*-FNT' ]
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: release # Value of the distributionManagement/repository/id field of the pom.xml

      - name: Build
        run: mvn clean install

      - name: Publish packages to Github packages
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
